_target_: agent.models.openai_api.OpenAIAPILanguageBackend
_partial_: true
client:
  _target_: huggingface_hub.InferenceClient
  base_url: https://api.openai.com/v1
  api_key: ${oc.env:OPENAI_API_KEY}
