from datetime import datetime
from typing import Any, Set

from pydantic import BaseModel

from agent.utils import pylogger
from agent.utils.utils import ListableEnum

log = pylogger.get_pylogger(__name__)

class MemKeyNotFoundError(RuntimeError):
    pass


class MemKey(str, ListableEnum):
    """An enumeration to represent the keys used in the memory."""

    # Generic keys
    AVAILABLE_ACTIONS = "_available_actions"  # Available actions for the agent to choose from
    EXTERNAL_ACTION = "_action"  # External actions the agent has taken
    NEXT_PLANNED_ACTION = "_next_planned_action"  # Next action the agent plans to take
    OBSERVATION = "_text_obs"  # Observations the agent has observed from the task
    RAW_ACTION_OUTPUT = "_raw_action_output"  # Raw outputs from the LLM
    REWARD = "_reward"  # Reward received from the environment by the agent at each timestep
    TASK_CATEGORY = "_task_category"  # Category of the task (only for some environments)
    POSITIVE_CLASS = "positive_class"  # The positive class in a binary classification task
    TARGET_CLASSES = "target_classes"
    THOUGHT = "_thought"  # Thoughts produced by the agent
    TASK_INFO = "_task_info"  # Generic information (dict) about the current task
    RETRIAL_CHAT_COMPLETION_TIME = "_retrial_chat_completion_time" # Time spent retrying to get a response from an LLM

    # Reflect keys
    REFLECTION = "_reflection"  # Reflections produced by the agent

    # CoT summary keys
    SUMMARIZE_COT = "_summarize_cot"  # detects if agent's CoTs need to be summaarized

    # Least-to-most keys
    SUBPROBLEM = "_subproblem"  # Subproblems produced by the agent

    # Self-consistency keys
    NEXT_PLANNED_ACTION_DIVERSE = "_next_possible_action_diverse"  # Diverse set of next possible actions (for SC)

    # # Swift-Sage keys
    # NEXT_PLANNED_ACTION_BUFFER = "_next_planned_action_buffer"  # Buffer of next actions to take (for SwiftSage)

    # RAG keys
    DB_QUERY = "_db_query"
    RAG_RETRIEVAL = "_rag_retrieval"

    # Google search keys
    GOOGLE_QUERY = "_google_query"  # Query used for Google search
    LINK_RETRIEVED = "_link_retrieved"  # Link retrieved from Google search
    NUM_CHUNKS = "_num_chunks"  # Number of chunks to summarize Google search
    SNIPPET_RETRIEVED = "_snippet_retrieved"  # Snippet retrieved from Google search
    SUMMARIZED_TEXT = "_summarized_text"  # Summarized text from Google search
    TEXT_RETRIEVED = "_text_retrieved"  # Text retrieved from Google search
    TITLE_RETRIEVED = "_title_retrieved"  # Title retrieved from Google search

    # Trajectory keys
    FULL_EPS_REWARDS = "_full_eps_rewards"  # Full list of rewards of the agent for the current episode
    FULL_EPS_TRAJECTORY = "_full_eps_trajectory"  # Full trajectory of the agent for the current episode
    TRAJECTORY = "_trajectory"  # Agent trajectory by timestep

    # ================================
    # Data-science task Keys
    # ================================
    CODE = "code"  # code used in prompt, can have holes or not (can be generated by agent)
    CODE_OUTPUT = "code_output"  # output of code ran in python interpreter
    CODE_ERROR = "code_error"  # error stack of code ran in python interpreter
    CODE_BLANK = "code_blank"  # element to be filled in a code blank
    CODE_FE = "fe_code" # feature engineering code
    CODE_TRAIN_IMG_TRANSFORM = "train_img_transform_code" # feature engineering code
    THINK_AND_CODE_MAX_REPETITIONS = "think_and_code_max_repetitions"  # Fail to generate valid code after max retrials
    THINK_AND_CODE_END_CHOICE = "think_and_code_end_choice"  # choice of the end of think and code flow
    MULTI_TRIAL_THINK_AND_CODE_LOOP_CHOICE = "multi_trial_think_and_code_loop_choice"  # choice of the end of think and code flow
    CODE_MODEL_TRAINING = "model_training_code" # model training code
    MODEL_PERF = "model_performance" # Performance of the model
    EDA = "eda"  # exploratory data analysis information
    TASK_DESCRIPTION = "task_description"  # information about the type of Kaggle task at hand
    DATA_DESCRIPTION = "data_description"  # more textual information about the data compared to EDA information
    FE_RAG = "fe_rag"  # feature engineering example retrieved for RAG
    MODELLING_RAG = "modelling_rag"  # modelling example retrieved for RAG
    TEMPLATES_RELATIVE_PATH = "templates_relative_path"  # rel. path to find the templates associated to the current run
    RAN_FE = "ran_fe"  # if feature engineering has been run already or not
    RAN_MODELLING = "ran_modelling"  # if modelling has been run already or not
    RAN_HYPEROPT = "ran_hyperopt"  # if hyperparameter optimization has been run already or not
    BEST_MODEL = "best_model"  # best model generated by agent, to be saved
    BO_ERROR = "bo_error"  # error stack when running BO
    BO_PERF = "bo_perf"  # performance after finishing to run BO
    BO_BEST_PARAMS = "bo_best_params"  # best hyper-parameters after finishing to run BO
    BO_MODEL_PARAMS_SEARCH_SPACE = "bo_model_search_space"  # best hyper-parameters after finishing to run BO
    SUBMISSION_LIST = "submission_list"  # list of submissions available so far
    CURRENT_SUBMISSION = "current_submission"  # submission that is currently created
    CURRENT_SUBMISSION_PERF = "current_submission_perf"  # performance of the submission that is currently created
    SELECTED_SUBMISSION = "selected_submission"  # submission selected for submission by the agent
    SENT_SUBMISSION_NAMES = "sent_submission_names"  # list of submissions already sent in the past for this competition
    SUBMISSION_SENT_SUCCESSFULLY = "submission_sent_successfully"  # flag if latest attempt to submit was successful
    SUMMARY_STEP = "summary_step"  # submission that is currently created
    SUBMISSION_SUMMARY = "submission_summary"  # summary of the entire submission
    SELECTED_SUBMISSIONS_BAG = "selected_submissions_bag"  # submissions selected for bagging for final submission
    SELECTED_SUBMISSIONS_BLEND = "selected_submissions_blend"  # submissions selected for blending for final submission
    REGRESSION_TARGET_VIEW = "regression_target_view"  # store views of the regression target DataFrame
    REGRESSION_TARGET_STATS = "regression_target_stats"  # store views of the stats of the regression target DataFrame
    IMG_DATA_STATISTICS = "img_data_statistics"  # e.g. normalization constants

    # ================================
    # Data Preprocessing Keys
    # ================================
    TASK_ID = "task_id"
    PATH_TO_PYTHON = "path_to_python"
    WORKSPACE_PATH = "workspace_path"
    DATA_PREP_PLAN = "data_prep_plan"  # plan object of the data prep pipeline
    FIM_TOKENS = "fim_tokens"  # dictionary of tokens for fill-in-the-middle prompting
    RAW_DATA_DIR = "raw_data_dir"
    FETCHED_RAW_DATA = "fetched_raw_data"
    RAW_TASK_DESCRIPTION = "raw_task_description"
    RAW_DATA_DESCRIPTION = "raw_data_description"
    RAW_DATA_VIEW = "raw_data_view"
    RAW_METRIC_DESCRIPTION = "raw_metric_description"
    RAW_TABLE_VIEW = "raw_table_view"
    RAW_TABLE_INFO = "raw_table_info"
    RAW_ID_COLUMN_NAME = "raw_id_column_name"
    RAW_TARGETS_COLUMN_NAMES = "raw_target_column_names"
    HAS_SAMPLE_SUBMISSION = "has_sample_submission"
    DETECT_SAMPLE_SUBMISSION_WITH_LLM = "detect_sample_submission_with_llm"  # use LLM to detect if not found otherwise
    SHOW_SAMPLE_SUBMISSION_IN_CODE = "show_sample_submission_in_code"
    SUMMARIZED_TASK_DESCRIPTION = "summarized_task_description"
    SUMMARIZED_DATA_DESCRIPTION = "summarized_data_description"
    SUMMARIZED_METRIC_DESCRIPTION = "summarized_metric_description"
    SUMMARIZED_SUBMISSION_FORMAT = "summarized_submission_format"
    SUMMARIZED_INPUTS_MODALITY_MAPS = "summarized_inputs_modality_maps"
    SUMMARIZED_TARGETS_MODALITY_MAPS = "summarized_targets_modality_maps"
    SUMMARIZED_TARGETS_MODALITY_TRANSFORMS = "summarized_modality_transforms"
    COLUMN_TYPES = "column_types"
    VALID_COLUMN_TYPES = "valid_column_types"
    COMMENT_COLUMN_TYPES = "comment_column_types"
    TRIGGER_HUMAN_TAKEOVER = "trigger_human_takeover"
    TAB_TRAIN_COLUMNS = "tab_train_columns"
    TAB_TRAIN_INFO = "tab_train_info"
    SAMPLE_SUBMISSION_HEAD = "sample_submission_head"
    ACTIVE_TABLE_VIEW = "active_table_view"  # used to store table views requested by the LLM at planning time
    ERROR_INSTRUCT = "error_instruct"  # errors transformed into list of instructions to avoid error repetition

    # RAG keys
    INPUT_RAG_EXAMPLES = "input_rag_examples"
    TARGET_RAG_EXAMPLES = "target_rag_examples"
    METRIC_RAG_EXAMPLES = "metric_rag_examples"
    SUBMISSION_FORMAT_RAG_EXAMPLES = "submission_format_rag_examples"
    CODE_RAG_EXAMPLES = "unit_test_rag_examples"
    UNIT_TEST_RAG_EXAMPLES = "unit_test_rag_examples"
    RAG_KEY = "rag_key"
    TURN_OFF_RAG_LOCALLY_ON_FAILURE = "turn_off_rag_locally_on_failure"
    RAG_LOCALLY_ACTIVE = "rag_locally_active"  # switch off rag locally if (rag active and examples don't help on issue)
    N_FAILURES_WITH_RAG_ACTIVE = "n_failures_with_rag_active"

    # POSITIVE_CLASS = "positive_class"
    TAB_TARGETS_STRUCT = "tab_targets_struct"
    FORMAT_ERROR = "format_error"
    SELECTED_METRIC = "selected_metric"

    # Transform memory keys
    INV_TRANSFORM_HEAD_VIEW_TAB = "inv_transform_head_view_tab"
    INV_TRANSFORM_HEAD_VIEW_TXT = "inv_transform_head_view_txt"
    INV_TRANSFORM_HEAD_VIEW_IMG = "inv_transform_head_view_img"
    PRED_TABLE_INFO_TAB = "pred_table_info_tab"
    PRED_TABLE_INFO_TXT = "pred_table_info_txt"
    PRED_TABLE_INFO_IMG = "pred_table_info_img"

    # general memory keys (to be used for all modalities, split and maps/transforms
    CODE_SUMMARY = "code_summary"  # summarize what the code does after it's been generated
    UNIT_TEST_ERROR_SUMMARY = "unit_test_error_summary"  # summarize the error of a unit test for use in prompt
    CODE_TEMPLATES = "code_templates"  # dictionary of lists of code templates
    UNIT_TESTS = "unit_tests"  # dictionary of lists of unit tests
    CODE_RAN = "code_ran"
    CODE_PASSED = "code_passed"
    LOOP_CODE_PASSED_CHOICE = "loop_code_passed_choice"
    UNIT_TEST_OUTPUT = "unit_test_output"
    UNIT_TEST_ERROR = "unit_test_error"
    UNIT_TEST_RAN = "unit_test_ran"
    UNIT_TEST_PASSED = "unit_test_passed"
    GROUP_UNIT_TEST_OUTPUT = "group_unit_test_output"
    GROUP_UNIT_TEST_ERROR = "group_unit_test_error"
    GROUP_UNIT_TEST_RAN = "group_unit_test_ran"
    GROUP_UNIT_TEST_PASSED = "group_unit_test_passed"
    GROUP_UNIT_TEST_NAME = "group_unit_test_name"

    # ================================
    # Ramp Keys
    # ================================
    RAMP_ACTION_PARAMS = "ramp_action_params_dict"
    RAMP_ACTION_EXECUTION_OUTPUT = "ramp_action_execution_output"
    RAMP_PLAN = "ramp_plan"
    RAMP_SELECTED_METRIC = "ramp_selected_metric"
    RAMP_ACTION = "ramp_action"
    MEAN_SCORE = "mean_score"
    RAMP_TAB_REGRESSION = "ramp_tab_regression"
    RAMP_TAB_CLASSIFICATION = "ramp_tab_classification"
    RAMP_HYPEROPT = "ramp_hyperopt"
    RAMP_SUBMISSION = "ramp_submission"
    RUNTIME = "runtime"

    FINAL_TEST_PASSED = "final_test_passed"
    FINAL_TEST_ERROR = "final_test_error"

    ACTION_VALUES = "action_values"

    KAGGLE_SCORE = "kaggle_score"  # For basic data science task
    FINAL_OBS_BDS = "final_obs_bds"  # For basic data science task


class MemoryEntry(BaseModel):
    """A class to represent a memory entry with creation time, content, and associated tags.

    Attributes:
        created_at (datetime): The time when the memory entry is created. Default is the current time.
        content (Any): The main content or body of the memory entry.
        tags (Union[Set[MemKey], list[MemKey]]): A set or list of tags associated with the memory entry.
    """

    created_at: datetime = datetime.now()
    content: Any
    tags: set[MemKey]


class Memory:
    """A class to manage the storing and retrieving of memory entries based on their associated
    tags and weights.

    Attributes:
        db (list[MemoryEntry]): A database(list) to store memory entries.
    """

    def __init__(self, initial_memories: list[MemoryEntry] | None = None):
        """Initializes the memory with an optional list of memory entries.

        Parameters:
            initial_memories (list[MemoryEntry] | None): An optional list of memory entries to pre-populate the memory.
        """
        if initial_memories is None:
            initial_memories = []

        self.db: list[MemoryEntry] = []
        self._initial_memories = initial_memories
        self.mem_keys = MemKey
        self.history_summary = None
        self.logger = None
        self.reset()

    def __contains__(self, tags: MemKey | list[MemKey]) -> bool:
        """Checks if the memory contains any memory entry with the given tags.

        Parameters:
            tags (MemKey | list[MemKey]): A list of tags to check for.

        Returns:
            bool: True if the memory contains any memory entry with the given tags, False otherwise.
        """

        for entry in self.db:
            if entry.tags.issuperset(set(tags)):
                return True
        return False

    def add_tags(self, ref_tag: MemKey, new_tags: MemKey | list[MemKey]) -> None:
        """Adds new tags to all instances of the reference tag in existing memory entries.

        Parameters:
            ref_tag (MemKey): The reference tag to which the new tags will be added.
            new_tags (MemKey | list[MemKey]): A list of new tags to be added.
        """

        new_tags = set(new_tags)

        assert ref_tag in set(self.mem_keys) and new_tags.issubset(set(self.mem_keys)), (
            "The reference tag and the new tags must be valid memory keys (MemKey enum). "
            "Please add them to the memory keys enum if you are intentionally creating new keys."
        )

        for entry in self.db:
            if ref_tag in entry.tags:
                entry.tags = entry.tags.union(new_tags)

    def delete(self, tags: MemKey | list[MemKey] | Set[MemKey]) -> None:
        """Deletes all instances of the tags from existing memory entries. If any memory entry has
        no tags, delete it.

        Parameters:
            tags (MemKey | list[MemKey]): A list of tags associated with the memory entries to be deleted.
        """
        if isinstance(tags, MemKey):
            tags = {tags}
        elif isinstance(tags, list):
            tags = set(tags)

        if not tags.issubset(set(self.mem_keys)):
            for tag in tags:
                if tag not in self.mem_keys:
                    raise RuntimeError(f"Trying to retrieve {tag} which in not a valid memory keys (MemKey enum).")

        inds_to_remove = []
        for ind, entry in enumerate(self.db):
            deleted_tags = entry.tags.intersection(tags)
            entry.tags = entry.tags - tags
            if len(entry.tags) == 0:
                if self.logger:
                    self.logger.log_metrics({f"memory:delete:{'|'.join(deleted_tags)}": entry})
                inds_to_remove.append(ind)
        for ind_to_remove in inds_to_remove[::-1]:
            self.db.pop(ind_to_remove)

    def rename(self, old_tag: MemKey, new_tag: MemKey) -> None:
        """Renames all instances of the old tag to the new tag in existing memory entries.

        Parameters:
            old_tag (MemKey): The old tag to be renamed.
            new_tag (MemKey): The new tag to replace the old tag.
        """

        assert old_tag in set(self.mem_keys) and new_tag in set(self.mem_keys), (
            "The old and new tags must be valid memory keys (MemKey enum). Please double check your tags, "
            "and add the new_tag to the memory keys enum if you are intentionally creating a new key."
        )

        for entry in self.db:
            if old_tag in entry.tags:
                entry.tags.remove(old_tag)
                entry.tags.add(new_tag)

    def reset(self) -> None:
        """Resets the memory to its initial state (the memories with which it was initialised)."""

        self.db = []
        for mem in self._initial_memories:
            self.store(mem.content, mem.tags)

    def retrieve(self, tags: MemKey | list[MemKey] | dict[MemKey, float]) -> Any:
        """Retrieves the content of the best matching memory entry based on the given tags and
        their respective weights. Returns the latest memory entry if multiple memory entries have
        the same score. If no scores are given, the default score will be 1.0.

        Parameters:
            tags (MemKey | list[MemKey] | dict[MemKey, float]): Tags with optional weights to retrieve
            the best matching memory entry.

        Returns:
            Any: The content of the best matching memory entry or None if the max calculated weight was =< 0
        """

        if isinstance(tags, str):
            tags = {tags: 1.0}

        if not isinstance(tags, dict):
            tags = {tag: 1.0 for tag in set(tags)}

        if not set(tags.keys()).issubset(set(self.mem_keys)):
            raise RuntimeError(
                "All retrieved tags must be valid memory keys (MemKey enum). "
                "Please double check your tags and try again."
            )

        best, best_score = None, float("-inf")

        for entry in self.db:
            score = sum([value for key, value in tags.items() if key in entry.tags])
            if score > best_score and score > 0:
                best = entry.content
                best_score = score

        return best

    def retrieve_all(self, tags: MemKey | list[MemKey] | dict[MemKey, float]) -> list[Any]:
        """Retrieves the content of all memory entries that have the highest score based on the
        given tags and their respective weights.

        Parameters:
            tags (MemKey | list[MemKey] | dict[MemKey, float]): Tags with optional weights to retrieve
            the best matching memory entry.

        Returns:
            list[Any]: A list containing the content of all memory entries that have the highest matching score,
            or an empty list if that score is <=0
        """

        if not isinstance(tags, dict):
            tags = {tag: 1.0 for tag in set(tags)}

        if not set(tags.keys()).issubset(set(self.mem_keys)):
            for tag in tags.keys():
                if tag not in self.mem_keys:
                    raise MemKeyNotFoundError(
                        f"Trying to retrieve {tag} which in not a valid memory keys (MemKey enum)."
                    )

        best, best_score = [], float("-inf")

        for entry in self.db:
            score = sum([value for key, value in tags.items() if key in entry.tags])
            if score > best_score and score > 0:
                best = [entry.content]
                best_score = score
            elif score == best_score:
                best.append(entry.content)

        return best

    def store(self, content: Any, tags: MemKey | list[MemKey] | Set[MemKey]) -> None:
        """Stores a new entry in the memory.

        Parameters:
            content (Any): The main content or body of the memory entry.
            tags (MemKey | list[MemKey]): A list of tags associated with the memory entry.
        """
        if isinstance(tags, str):
            tags = {tags}
        if isinstance(tags, list):
            tags = set(tags)

        if not tags.issubset(set(self.mem_keys)):
            for tag in tags:
                if tag not in self.mem_keys:
                    raise RuntimeError(f"Trying to retrieve {tag} which in not a valid memory keys (MemKey enum).")

        if self.logger:
            self.logger.log_metrics({f"memory:store:{'|'.join(tags)}": content})

        # By inserting at the beginning, newer memory entries will get priority
        self.db.insert(0, MemoryEntry(content=content, tags=tags))


if __name__ == "__main__":
    memory = Memory()

    # memory.store("This is a random system prompt.", {"system", "prompt", "random", "friendly"})
    # memory.store("This is a random user prompt for alfworld.", {"user", "prompt", "alfworld", "random"})
    # memory.store("This is a random user prompt for babyai.", {"user", "prompt", "babyai"})
    #
    # print(memory.retrieve({"system": 2.0, "prompt": 1.0, "alfworld": 1.0}))
