import argparse
import os
import pathlib

import lightning as L
import numpy as np
import pandas as pd
import torch.optim
from torch import nn
from torch.utils.data import DataLoader
from tqdm import tqdm

torch.manual_seed(123)

from solve_params import TRAIN_BATCH_SIZE, TEST_BATCH_SIZE, NUM_WORKERS

try:
    from map_dataset import MapDataset, map_dataset_collate_function, Identity
except ImportError:
    current_dir = str(pathlib.Path(__file__).parent.resolve())
    print(f"map_dataset should be in {current_dir}")
    raise

# Import transforms
try:
    from tab_fe import DataPreprocessor

    tab_fe_preprocess = DataPreprocessor()
except ImportError as e:
    tab_fe_preprocess = None

try:
    from tab_regression_target_scaler import tab_regression_target_scaler as custom_tab_regression_scaler
except ImportError as e:
    custom_tab_regression_scaler = None

try:
    from code_transform_tab_target_train import tab_target_transform, tab_target_inverse_transform, enc, \
        class_names_columns_classification
except ImportError as e:
    tab_target_transform = Identity()
    tab_target_inverse_transform = Identity()
    enc = None
    class_names_columns_classification = []

try:
    from code_transform_img_target_train import img_target_transform, img_target_inverse_transform
except ImportError as e:
    img_target_transform = Identity()
    img_target_inverse_transform = Identity()

try:
    from code_transform_txt_target_train import txt_target_transform, txt_target_inverse_transform
except ImportError as e:
    txt_target_transform = Identity()
    txt_target_inverse_transform = Identity()

try:
    from img_embed import ImageEmbedder
except ImportError as e:
    ImageEmbedder = None
try:
    from img_transform import CustomTrainImageInputTransform, CustomTestImageInputTransform
except ImportError as e:
    CustomTrainImageInputTransform = None
    CustomTestImageInputTransform = None

try:
    from txt_embed import TextEmbedder
except ImportError as e:
    TextEmbedder = None

# Import decoders
try:
    from tab_head import TabularHead, regression_loss, classification_loss
except ImportError as e:
    TabularHead = None
    regression_loss = None
    classification_loss = None

try:
    from img_head import get_img_head, img_loss
except ImportError as e:
    get_img_head = None
    img_loss = None

try:
    from txt_head import get_txt_head, txt_loss
except ImportError as e:
    get_txt_head = None
    txt_loss = None

submission_format_functions = []
submission_names = []
try:
    from code_submission_format import df_to_submission_format  # this is generated by an LLM

    submission_format_functions.append(df_to_submission_format)
    submission_names.append('submission.csv')
except ImportError as e:
    df_to_submission_format = None
try:
    from code_submission_format_alt import df_to_submission_format as df_to_submission_format_alt

    submission_format_functions.append(df_to_submission_format_alt)
    submission_names.append('submission_alt.csv')
except ImportError as e:
    df_to_submission_format_alt = None
if len(submission_format_functions) == 0:
    raise ValueError("No valid submission format functions found in setup!")


# --- Build dataset
def get_optional_path(path: pathlib.Path) -> str | None:
    """ Return path if it exists, else return None """
    if path.exists():
        return str(path)


def _format_submission_dtypes(formatted_submission: pd.DataFrame) -> pd.DataFrame:
    sample_submission = pd.read_csv("sample_submission.csv")
    for column in sample_submission:
        if sample_submission[column].isna().all():
            try:
                if np.array_equal(formatted_submission[column], formatted_submission[column].astype(int)):
                    formatted_submission[column] = formatted_submission[column].round().astype(int)
            except (ValueError, RuntimeError) as e:
                print(e)
                pass
        else:
            try:
                if (np.issubdtype(sample_submission[column].dtype, np.integer) and
                        np.array_equal(formatted_submission[column], formatted_submission[column].astype(int))):
                    formatted_submission[column] = formatted_submission[column].round().astype(int)
            except (ValueError, RuntimeError) as e:
                print(e)
                pass
            try:
                if (np.issubdtype(sample_submission[column].dtype, np.float32) and
                        np.array_equal(formatted_submission[column], formatted_submission[column].astype(float))):
                    formatted_submission[column] = formatted_submission[column].astype(float)
            except (ValueError, RuntimeError) as e:
                print(e)
                pass
            # else:
            #     formatted_submission[column] = formatted_submission[column].astype(sample_submission[column].dtypes)
    return formatted_submission


def main() -> None:
    model = SubmissionModel.load_from_checkpoint(checkpoint_path="./best_model.ckpt")
    model.eval()

    free_gpus = [device_id for device_id in range(torch.cuda.device_count()) if
                 torch.cuda.utilization(device_id) == 0]
    model.to(free_gpus[0] if len(free_gpus) else 'cpu')

    print(f"[START] Generate test predictions")
    test_submission, _, _ = model.get_submissions(dataloader=test_dataloader)
    for submission_format_func, submission_name in zip(submission_format_functions, submission_names):
        formatted_sub = submission_format_func(test_submission)
        formatted_sub.to_csv(
            os.path.join(str(pathlib.Path(__file__).parent), 'regenerated_formatted_' + submission_name), index=False)
        formatted_sub = _format_submission_dtypes(formatted_sub)
        formatted_sub.to_csv(
            os.path.join(str(pathlib.Path(__file__).parent), 'regenerated_formatted_dtype_' + submission_name),
            index=False)

    # formatted_submission = df_to_submission_format(test_submission)
    # formatted_submission_alt = df_to_submission_format_alt(test_submission)
    # formatted_submission.to_csv('regenerated_formatted_submission', index=False)
    # formatted_submission_alt.to_csv('regenerated_formatted_submission_alt', index=False)
    #
    # # Format and save the submission
    # formatted_submission = _format_submission_dtypes(formatted_submission)
    # formatted_submission_alt = _format_submission_dtypes(formatted_submission_alt)
    # formatted_submission.to_csv('regenerated_formatted_submission_fix_dtypes', index=False)
    # formatted_submission_alt.to_csv('regenerated_formatted_submission_alt_fix_dtypes', index=False)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--prepared_workspace", type=str, required=True)
    parser.add_argument("--batch_size", type=int, default=TEST_BATCH_SIZE)
    parser.add_argument("--dataloader_workers", type=int, default=NUM_WORKERS)
    args = parser.parse_args()
    prepared_workspace = pathlib.Path(args.prepared_workspace)
    if args.batch_size != TEST_BATCH_SIZE:
        TEST_BATCH_SIZE = args.batch_size
    if args.dataloader_workers != NUM_WORKERS:
        NUM_WORKERS = args.dataloader_workers

    tab_input_map_path = get_optional_path(prepared_workspace / "train_tab_input_map.csv")
    img_input_map_path = get_optional_path(prepared_workspace / "train_img_input_map.csv")
    txt_input_map_path = get_optional_path(prepared_workspace / "train_txt_input_map.csv")
    tab_target_map_path = get_optional_path(prepared_workspace / "train_tab_target_map.csv")
    img_target_map_path = get_optional_path(prepared_workspace / "train_img_target_map.csv")
    txt_target_map_path = get_optional_path(prepared_workspace / "train_txt_target_map.csv")

    test_tab_input_map_path = get_optional_path(prepared_workspace / "test_tab_input_map.csv")
    test_img_input_map_path = get_optional_path(prepared_workspace / "test_img_input_map.csv")
    test_txt_input_map_path = get_optional_path(prepared_workspace / "test_txt_input_map.csv")

    dataset, test_dataset = MapDataset.create_train_test_datasets(
        train_tab_input_map_path=tab_input_map_path,
        train_img_input_map_path=img_input_map_path,
        train_txt_input_map_path=txt_input_map_path,
        train_tab_target_map_path=tab_target_map_path,
        train_img_target_map_path=img_target_map_path,
        train_txt_target_map_path=txt_target_map_path,
        test_tab_input_map_path=test_tab_input_map_path,
        test_img_input_map_path=test_img_input_map_path,
        test_txt_input_map_path=test_txt_input_map_path,
        tab_input_transform=Identity(),
        img_input_transform=Identity(),
        txt_input_transform=Identity(),
        tab_target_transform=tab_target_transform,
        img_target_transform=img_target_transform,
        txt_target_transform=txt_target_transform,
        tab_target_inverse_transform=tab_target_inverse_transform,
        img_target_inverse_transform=img_target_inverse_transform,
        txt_target_inverse_transform=txt_target_inverse_transform,
        custom_tab_regression_scaler=custom_tab_regression_scaler,
        custom_img_train_input_transform=CustomTrainImageInputTransform,
        custom_img_test_input_transform=CustomTestImageInputTransform,
        tab_fe=tab_fe_preprocess.preprocess if tab_fe_preprocess else None
    )

    if os.getenv("AGENT_DEBUG"):
        val_proportion = 0.05
    else:
        val_proportion = 0.25
    train_dataset, validation_dataset = torch.utils.data.random_split(dataset, [1 - val_proportion, val_proportion])


    def get_data_loaders():
        train_dl = DataLoader(train_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True, pin_memory=True,
                              prefetch_factor=2, persistent_workers=True, collate_fn=map_dataset_collate_function,
                              num_workers=NUM_WORKERS)

        valid_dl = DataLoader(validation_dataset, batch_size=TEST_BATCH_SIZE, shuffle=False, pin_memory=True,
                              prefetch_factor=2, collate_fn=map_dataset_collate_function, num_workers=NUM_WORKERS)

        test_dl = DataLoader(test_dataset, batch_size=TEST_BATCH_SIZE, shuffle=False, pin_memory=True,
                             prefetch_factor=2, collate_fn=map_dataset_collate_function, num_workers=NUM_WORKERS)

        return train_dl, valid_dl, test_dl


    train_dataloader, validation_dataloader, test_dataloader = get_data_loaders()

    # Compute output_dim from inputs
    train_input_sample = next(iter(train_dataloader))

    try:
        from code_metric import metric_function
    except ImportError:
        raise

    tab_inputs_batch, img_inputs_batch, txt_inputs_batch = None, None, None
    tab_targets_batch, img_targets_batch, txt_targets_batch = None, None, None
    # Get some dimensionality info
    for (indices, (tab_inputs_batch, img_inputs_batch, txt_inputs_batch),
         (tab_targets_batch, img_targets_batch, txt_targets_batch)) in train_dataloader:
        break

    embed_dim = 0

    if tab_targets_batch is not None:
        OUTPUT_DIM = tab_targets_batch.shape[1]
    elif img_targets_batch is not None:
        OUTPUT_DIM = img_targets_batch.shape[1]
    elif txt_targets_batch is not None:
        OUTPUT_DIM = txt_targets_batch.shape[1]

    if tab_inputs_batch is not None:
        from tab_embed import tab_feature_engineer, TabularEmbedder, TAB_EMBED_DIM

        tab_input_dim = tab_feature_engineer(tab_inputs_batch).shape[-1]

        tab_embedder = TabularEmbedder(input_dim=tab_input_dim, embed_dim=TAB_EMBED_DIM)
        embed_dim += TAB_EMBED_DIM
    else:
        tab_embedder = None
        tab_feature_engineer = None

    if ImageEmbedder is not None:
        assert issubclass(ImageEmbedder, nn.Module)


        class AuxImageEmbedder(ImageEmbedder):
            """ Wrap ImageEmbedder to deal with the input dimension """

            def forward(self, x: torch.Tensor):
                """
                Args:
                    x: dimension (batch, n_images_per_id, n_channels, height, width)

                Returns:
                     y: dimension (batch, embed_dim)  --> the `n_images_per_id` are flatten
                """
                y = super().forward(x.view(-1, *x.shape[-3:]))
                return y.reshape(len(x), -1)


        img_embedder = AuxImageEmbedder()
        embed_dim += img_embedder(img_inputs_batch[:2]).shape[-1]
    else:
        img_embedder = None

    if TextEmbedder is not None:
        assert issubclass(TextEmbedder, nn.Module)


        class AuxTextEmbedder(TextEmbedder):
            """ Wrap TextEmbedder to deal with the input dimension """

            def forward(self, x: pd.DataFrame | np.ndarray | torch.Tensor):
                """
                Args:
                    x: dimension (batch, n_texts_per_id)

                Returns:
                     y: dimension (batch, embed_dim)  --> the `n_texts_per_id` are flattened
                """
                bsz = x.shape[0]
                if isinstance(x, pd.DataFrame):
                    x = x.values
                    x = x.reshape(-1, *x.shape[1:])
                    x = x.flatten().tolist()
                # make sure input is on same device as model params
                y = super(AuxTextEmbedder, self).forward(x)
                return y.reshape(bsz, -1)


        txt_embedder = AuxTextEmbedder()
        embed_dim += txt_embedder(txt_inputs_batch).shape[-1]
    else:
        txt_embedder = None


    class SubmissionModel(L.LightningModule):
        def __init__(self, learning_rate=1e-5, optimizer_choice='adam'):
            super().__init__()
            self.tab_fe = tab_feature_engineer
            self.tab_embedder = tab_embedder
            self.img_embedder = img_embedder
            self.txt_embedder = txt_embedder

            self.tab_head = TabularHead(embed_dim=embed_dim, output_dim=OUTPUT_DIM)
            self.learning_rate = learning_rate
            self.optimizer_choice = optimizer_choice

            if get_img_head is None:
                self.img_head = None
            else:
                self.img_head = get_img_head()
            if get_txt_head is None:
                self.txt_head = None
            else:
                self.txt_head = get_txt_head()

            self.tab_regression_loss = regression_loss
            self.tab_classification_loss = classification_loss
            self.img_loss = img_loss
            self.txt_loss = txt_loss

            self.unfreeze_epoch = None

        def tab_loss(self, pred: torch.Tensor, target: pd.DataFrame) -> float:
            assert pred.shape == target.shape, (pred.shape, target.shape)
            target = torch.from_numpy(target.values).to(pred)
            if pred.ndim == 1:
                pred = pred.unsqueeze(0)
                target = target.unsqueeze(0)
            loss = 0.

            # If enc is not None that means we have classification target
            if enc:
                columns_class_name = list(enc.get_feature_names_out(class_names_columns_classification))

                classification_pred = pred[:, :len(columns_class_name)]
                classification_target = target[:, :len(columns_class_name)]

                groups_label = enc.categories_
                idx_start = 0
                for group in groups_label:
                    group_pred = classification_pred[:, idx_start:idx_start + len(group)]
                    group_target = classification_target[:, idx_start:idx_start + len(group)]
                    idx_start += len(group)

                    loss += self.tab_classification_loss(group_pred, group_target)

                if pred.shape[-1] > len(columns_class_name):
                    regression_pred = pred[:, len(columns_class_name):]
                    regression_target = target[:, len(columns_class_name):]
                    loss += self.tab_regression_loss(regression_pred, regression_target)

            # Full regression
            else:
                loss += self.tab_regression_loss(pred, target)
            return loss

        def embed(self, tab, img, txt) -> tuple[torch.Tensor | None, torch.Tensor | None, torch.Tensor | None]:
            """ Get the embeddings for each modality """

            if self.tab_embedder is None:
                tab_embed = None
            else:
                tab = self.tab_fe(tab)
                tab = torch.tensor(tab.values).to(device=self.device, dtype=self.dtype)
                tab_embed = self.tab_embedder(tab)
            if self.img_embedder is None:
                img_embed = None
            else:
                img = img.to(device=self.device, dtype=self.dtype)
                img_embed = self.img_embedder(img)
            if self.txt_embedder is None:
                txt_embed = None
            else:
                self.txt_embedder.to(self.device)
                txt_embed = self.txt_embedder(txt)
            return tab_embed, img_embed, txt_embed

        def decode(self, latent_embed: torch.Tensor) -> tuple[
            torch.Tensor | None, torch.Tensor | None, torch.Tensor | None]:
            """ Obtain logits / images / next tokens predictions given the latent embedding """
            if self.tab_head is None:
                pred_tab = None
            else:
                pred_tab = self.tab_head(latent_embed)
            if self.img_head is None:
                pred_img = None
            else:
                pred_img = self.img_head(latent_embed)
            if self.txt_head is None:
                pred_txt = None
            else:
                pred_txt = self.txt_head(latent_embed)
            return pred_tab, pred_img, pred_txt

        def forward(self, tab: pd.DataFrame, img: torch.Tensor, txt: pd.DataFrame) -> tuple[
            torch.Tensor | None, torch.Tensor | None, torch.Tensor | None]:
            tab_embed, img_embed, txt_embed = self.embed(tab=tab, img=img, txt=txt)

            to_fuse = [embed for embed in [tab_embed, img_embed, txt_embed] if embed is not None]
            assert len(to_fuse) > 0
            # Fuse the embeddings of each modality
            latent_embed = torch.cat(to_fuse, dim=1)
            return self.decode(latent_embed=latent_embed)

        def training_step(self, batch, batch_idx) -> torch.Tensor:
            # training_step defines the train loop.
            (indices, (tab_inputs_batch, img_inputs_batch, txt_inputs_batch),
             (tab_targets_batch, img_targets_batch, txt_targets_batch)) = batch

            pred_tab, pred_img, pred_txt = self.forward(tab=tab_inputs_batch, img=img_inputs_batch,
                                                        txt=txt_inputs_batch)

            loss = 0.
            if tab_targets_batch is not None:
                loss += self.tab_loss(pred=pred_tab, target=tab_targets_batch).mean()
            if self.img_loss is not None:
                loss += self.img_loss(pred_img, img_targets_batch).mean()
            if self.txt_loss:
                loss += self.txt_loss(pred_txt, txt_targets_batch).mean()

            self.log("train_loss", loss, prog_bar=True, on_step=False, on_epoch=True, batch_size=len(indices))
            return loss

        @staticmethod
        def get_param_groups(model: nn.Module | None, **kwargs) -> dict[str, ...] | None:
            if model is None:
                return None
            else:
                return {"params": model.parameters(), **kwargs}

        def configure_optimizers(self) -> torch.optim.Optimizer:
            groups = [
                self.get_param_groups(model=self.tab_embedder, lr=self.learning_rate),
                self.get_param_groups(model=self.tab_head, lr=self.learning_rate),
                self.get_param_groups(model=self.img_embedder, lr=self.learning_rate),
                self.get_param_groups(model=self.img_head, lr=self.learning_rate),
                self.get_param_groups(model=self.txt_embedder, lr=self.learning_rate),
                self.get_param_groups(model=self.txt_head, lr=self.learning_rate),
            ]

            params = [group for group in groups if group is not None]

            if self.optimizer_choice == "adam":
                optimizer = torch.optim.Adam(params, lr=self.learning_rate)
            elif self.optimizer_choice == "sgd":
                optimizer = torch.optim.SGD(params, lr=self.learning_rate)
            elif self.optimizer_choice == "adamw":
                optimizer = torch.optim.AdamW(params, lr=self.learning_rate)
            else:
                raise ValueError(f"Unsupported optimizer: {self.optimizer_choice}")

            return optimizer

        def on_train_start(self) -> None:
            self.unfreeze_epoch = 10

        def on_train_epoch_start(self) -> None:
            if self.current_epoch == self.unfreeze_epoch and self.img_embedder:
                print(f"Unfreezing layers at epoch {self.current_epoch}")
                self.img_embedder.unfreeze(n_last_layers=3)

        def validation_step(self, batch, batch_idx):
            """ Run """
            # training_step defines the train loop.
            (indices, (tab_inputs_batch, img_inputs_batch, txt_inputs_batch),
             (tab_targets_batch, img_targets_batch, txt_targets_batch)) = batch

            pred_tab, pred_img, pred_txt = self.forward(tab=tab_inputs_batch, img=img_inputs_batch,
                                                        txt=txt_inputs_batch)

            loss = 0.
            if self.tab_loss is not None:
                loss += self.tab_loss(pred_tab, tab_targets_batch)
            if self.img_loss is not None:
                loss += self.img_loss(pred_img, img_targets_batch)
            if self.txt_loss:
                loss += self.txt_loss(pred_txt, txt_targets_batch)

            self.log("valid_loss", loss, prog_bar=True, on_step=False, on_epoch=True, batch_size=len(indices))

        def get_submissions(self, dataloader: DataLoader) -> tuple[pd.DataFrame, pd.DataFrame]:
            """ Get submissions for each element of the dataloader """
            submission = pd.DataFrame([])
            target = pd.DataFrame([])

            img_preds = []
            txt_preds = []

            indices = []
            for batch in tqdm(dataloader):
                (indices_batch, (tab_inputs_batch, img_inputs_batch, txt_inputs_batch),
                 (tab_targets_batch, img_targets_batch, txt_targets_batch)) = batch

                indices += list(indices_batch)

                with torch.no_grad():
                    pred_tab, pred_img, pred_txt = self.forward(
                        tab=tab_inputs_batch, img=img_inputs_batch, txt=txt_inputs_batch
                    )

                if pred_tab is not None:

                    # Classification target
                    if enc:
                        softmax = nn.Softmax(dim=1)
                        columns_class_name = list(enc.get_feature_names_out(class_names_columns_classification))

                        classification_pred = pred_tab[:, :len(columns_class_name)].clone()

                        groups_label = enc.categories_
                        idx_start = 0
                        for group in groups_label:
                            group_pred = classification_pred[:, idx_start:idx_start + len(group)]
                            pred_tab[:, idx_start:idx_start + len(group)] = softmax(group_pred)
                            idx_start += len(group)

                    pred_tab = pred_tab.cpu().numpy()
                    pred_tab = dataset.tab_target_inverse_transform(pred_tab, indices_batch)

                    submission = pd.concat([submission, pred_tab])

                if pred_img is not None:
                    assert not isinstance(dataset.img_target_inverse_transform,
                                          Identity), "Predicted images must be transformed"
                    pred_img = dataset.img_target_inverse_transform(pred_img)
                    img_preds.append(pred_img)

                if pred_txt is not None:
                    pred_txt = dataset.txt_target_inverse_transform(pred_txt)
                    txt_preds.append(pred_txt)

                if tab_targets_batch is not None and len(tab_targets_batch) > 0:
                    tab_targets_batch = dataset.tab_target_inverse_transform(tab_targets_batch.values, indices_batch)
                    target = pd.concat([target, tab_targets_batch])

                if img_targets_batch is not None and len(img_targets_batch) > 0:
                    img_targets_batch = dataset.img_target_inverse_transform(img_targets_batch.values, indices_batch)
                    target = pd.concat([target, img_targets_batch])

                if txt_targets_batch is not None and len(txt_targets_batch.columns) > 0:
                    txt_targets_batch = dataset.txt_target_inverse_transform(txt_targets_batch.values, indices_batch)
                    target = pd.concat([target, txt_targets_batch])

            return submission, target


    main()
