import pathlib
import warnings
from typing import Callable

import numpy as np
import torch
from torch.utils.data import DataLoader, WeightedRandomSampler

from solve_params import NUM_WORKERS

original_showwarning = warnings.showwarning

try:
    from map_dataset import Identity, MapDataset, map_dataset_collate_function
except ImportError:
    current_dir = str(pathlib.Path(__file__).parent.resolve())
    print(f"map_dataset should be in {current_dir}")
    raise

try:
    from img_transform import CustomTestImageInputTransform, CustomTrainImageInputTransform
except ImportError:
    CustomTrainImageInputTransform = None
    CustomTestImageInputTransform = None

try:
    from code_transform_tab_target_train import (
        class_names_columns_classification,
        enc,
        tab_target_inverse_transform,
        tab_target_transform,
    )
except ImportError:
    tab_target_transform = Identity()
    tab_target_inverse_transform = Identity()
    enc = None
    class_names_columns_classification = []

try:
    from class_imbalance import calculate_class_weights
except ImportError:
    calculate_class_weights = None


submission_format_functions = []
submission_names = []
try:
    from code_submission_format import df_to_submission_format  # this is generated by an LLM

    submission_format_functions.append(df_to_submission_format)
    submission_names.append("submission.csv")
except ImportError:
    df_to_submission_format = None
try:
    from code_submission_format_alt import df_to_submission_format as df_to_submission_format_alt

    submission_format_functions.append(df_to_submission_format_alt)
    submission_names.append("submission_alt.csv")
except ImportError:
    df_to_submission_format_alt = None
if len(submission_format_functions) == 0:
    raise ValueError("No valid submission format functions found in setup!")

try:
    from tab_fe import DataPreprocessor

    tab_fe_preprocess = DataPreprocessor()
except ImportError:
    tab_fe_preprocess = None

try:
    from tab_regression_target_scaler import tab_regression_target_scaler as custom_tab_regression_scaler
except ImportError:
    custom_tab_regression_scaler = None

try:
    from code_transform_img_target_train import img_target_inverse_transform, img_target_transform
except ImportError:
    img_target_transform = Identity()
    img_target_inverse_transform = Identity()

try:
    from code_transform_txt_target_train import txt_target_inverse_transform, txt_target_transform
except ImportError:
    txt_target_transform = Identity()
    txt_target_inverse_transform = Identity()


# Some code_metric and code_submission_format modules patch warnings.showarning
# with a non-existent path, so we save the unpatched version and restore it
warnings.showwarning = original_showwarning



def get_data_loader(
        dataset, batch_size: int, is_sample_required: bool, is_shuffle_required: bool
) -> DataLoader:
    if is_sample_required and calculate_class_weights is not None:
        assert(isinstance(calculate_class_weights, Callable))
        target_df = dataset.tab_target_map.copy(deep=True)
        target_df.drop(columns='id', errors='ignore', inplace=True)
        target_columns = target_df.columns.tolist()
        weight_vector = calculate_class_weights(target_df=target_df, target_columns=target_columns)
        weight_vector = torch.from_numpy(weight_vector.astype(np.float32))
        sampler = WeightedRandomSampler(weight_vector, len(weight_vector))
        shuffle = False
    elif is_shuffle_required:
        sampler = None
        shuffle = True
    else:
        sampler = None
        shuffle = False

    dataset_dl = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        pin_memory=True,
        prefetch_factor=2,
        # persistent_workers=True,
        collate_fn=map_dataset_collate_function,
        num_workers=NUM_WORKERS,
        sampler=sampler
    )

    return dataset_dl


class NanLossError(Exception):
    """ raise when there is a nan loss"""
    pass

